# Note: If you want to deploy to a GitHub user site (user.github.io), change baseurl to /
baseurl: ""
title: Baihao Zhang
# Whether the header (with large title and subtitle) should be displayed
header: true
subtitle: PhD candidate in Modern History and German Studies
author: Baihao Zhang
email: baihao.zhang [at] sorbonne-nouvelle [dot] fr
description: Personal Website
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: /articles/:categories/:year/:month/:day/:title.html
timezone: Europe/Berlin
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'DeployToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
git:
  branch: src
